### ISSUE TITLE
Details Schema tempalte error: The property offers is not recognized by Google for an object of type Place.

### ISSUE THREAD

**Issue by yoursiteneedsme** [antonioortegajr/idx-page-templates#4]
Error found: OFFERS: The property offers is not recognized by Google for an object of type Place.
see attached
Tested on AID 6104
https://jasper-real-estate.sell-4free.net/idx/details/listing/a347/201907592/763-E-Shore-Drive-Culver-IN-46511
![snip20190306_1](https://user-images.githubusercontent.com/31107658/53889419-69bbdb80-3ff4-11e9-976e-0b805a833b8e.png)

**Comment by antonioortegajr** [comment]
That is not an error, that is a warning. I will still look into it, but this is less a bug since it's warning.

**Comment by antonioortegajr** [comment]
I checked out realtor.com, redfin, and estately details pages. They all have warnings in the validator shown above, but they also showed the open house data in the google SERPs.

**Comment by antonioortegajr** [comment]
looking around seems like the places using span tags or meta tags are having errors and warning. While those providing an array of object have fewer warnings. Maybe that is a better approach? 

Example:

`<script type='application/ld+json'>
[{
	"@context": "http://schema.org/",
	"@type": "SingleFamilyResidence",
	"address": {
		"@type": "PostalAddress",
		"streetAddress": "{{ streetNumber }} {{ streetName }}", 
		"addressLocality": "{{ cityName }}",
		"addressRegion": "{{ stateAbrv }}",
		"postalCode": "{{ zipcode }}"
	},
	"image": "{{ imageData.1.url }}",
	"geo": {
		"@type": "GeoCoordinates",
		"latitude": {{ latitude }},
		"longitude": {{ longitude }}
	}
}, {
	"@context": "http://schema.org/",
	"@type": "Product",
	"name": "{{ streetNumber }} {{ streetName }}",
	"description": "Home For Sale - {{ streetNumber }} {{ streetName }}, {{ cityName }}, {{ stateAbrv }} {{ zipcode }}",
	"url": "{{ propertyLink }}",
	"offers": {
		"@type": "Offer",
		"priceCurrency": "USD",
		"url": "{{ propertyLink }}",
		"price": {{listingPrice | replace({"," : ""}) | replace({"$" : ""}) }}
	},
	"image": ["{{ imageData.1.url }"}, "{{ imageData.2.url }"}]
}, {
	"@context": "http://schema.org/",
	"@type": "Event",
	"name": "Open House - {{ oh.freeFormTime }}",
	"description": "Open house {{ oh.freeFormDate | date('Y-m-d') }}, 11am-1pm at {{ streetNumber }} {{ streetName }}",
	"startDate": "{{ oh.freeFormDate | date('Y-m-d') }}",
	"endDate": "{{ oh.freeFormDate | date('Y-m-d') }}",
	"url": "{{ propertyLink }}",
	"location": {
		"@type": "Place",
		"name": "{{ streetNumber }} {{ streetName }}",
		"address": {
			"@type": "PostalAddress",
			"streetAddress": "{{ streetNumber }} {{ streetName }}",
			"postalCode": "{{ zipcode }}",
			"addressLocality": "{{ cityName }}",
			"addressRegion": "{{ stateAbrv }}"
		},
		"geo": {
			"@type": "GeoCoordinates",
			"latitude": {{ latitude }},
			"longitude": {{ longitude }}
		}
	},
	"offers": {
		"@type": "Offer",
		"url": "{{ propertyLink }}",
		"price": {{listingPrice | replace({"," : ""}) | replace({"$" : ""}) }},
		"priceCurrency": "USD"
	},
	"image": "{{ imageData.1.url }}"
}]</script>`

**Comment by antonioortegajr** [comment]
I also like that all the data objects is in one array.
also "Google recommends using JSON-LD for structured data whenever possible."
https://developers.google.com/search/docs/guides/intro-structured-data

**Comment by antonioortegajr** [comment]
OK added a new development branch with json schema as an array of json objects. https://github.com/antonioortegajr/idx-page-templates/blob/dev/details-schema/details.php

@yoursiteneedsme  Can we test this one with AID mentioned above? There are still some warnings(well more), but this is more closely like what I am seeing working else where. And ideally I would like to see the open hose data show in the google SERPS first then research each individual  warning further.

**Comment by antonioortegajr** [comment]
OK I moved the offers object and seems to pass now. However the following warnings (for fields not provided) are now there:
* Product
    * availability
    * priceValidUntil
    * aggregateRating
    * brand
    * review
    * sku
    * ? This Product is missing a global identifier (e.g. isbn, mpn or gtin8). Please see documentation for valid identifiers.

* Event
    * availability - in offer
    * validFrom - in offer
    * performer

**Comment by yoursiteneedsme** [comment]
@antonioortegajr I will have Cheyenne look at this and get back with you!

**Comment by antonioortegajr** [comment]
This has been updated and the 3 remaining warnings:
* availability
* validFrom
* validFrom

Are not required so closing this issue.
